version: 2
jobs:
  build:
    docker:
    #https://circleci.com/docs/building-docker-images/
      - image: cimg/go:1.17
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD  
          
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Pre Install
          command: |
            echo "nothing needs to be installed"
      - run:
          name: before_script
          command: |
            echo "no tests"
      - run:
          name: Verify Docker version
          command: |
            docker --version
      - run:
          name: Build Docker image 
          command: |
            docker build -t simple-node .
            docker tag simple-node $DOCKER_USERNAME/simple-node:latest
      - run:
          name: Run after_success
          command: |
            echo "$DOCKER_PASSWORD" | echo "$DOCKER_USERNAME"
      - deploy:
          name: Push application Docker image
          command: |
            docker push $DOCKER_USERNAME/simple-node:latest