version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - run:
        # installs a docker client that will be used to run the docker commands
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            
      - run:
          name: Pre Install
          command: |
            echo "nothing needs to be installed"
      - run:
          name: before_script
          command: |
            echo "no tests"
      - run:
          name: Verify Docker version
          command: |
            docker --version
      - run:
          name: Build Docker image 
          command: |
            docker build -t simple-node .
            docker tag simple-node mohammedshalan/simple-node:latest
      - run:
          name: Run after_success
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - deploy:
          name: Push application Docker image
          command: |
            docker push mohammedshalan/simple-node